### ISSUE TITLE
Battery drain & notifications issues

### ISSUE THREAD

**Issue by DIDIZ0MBIEX** [roothide/Bootstrap#109]
Either bootstrap or serotonin is causing a massive battery drain 

Using app enabler stops notifications showing up in the notification settings and stops notification coming through for those apps

**Comment by dleovl** [comment]
Battery drain can be attributed to `mineek/Serotonin`, there are no mass reports of battery drain with just the RootHide Bootstrap by itself.

Notifications, duplicate of #2.
