### ISSUE TITLE
has it been tested on M1 17.0?

### ISSUE THREAD

**Issue by ak4zh** [roothide/Bootstrap#11]
I built Bootstrap.tipa and installed it through TrollStore 2 on my iPad 12.9 M1 running iOS 17.0. However, I encountered a problem where attempting to open Bootstrap results in an immediate crash of Bootstrap.

Could you please confirm if Bootstrap has been tested and is expected to work with iPad 12.9 M1 on iOS 17.0? Additionally, if there are any known issues or troubleshooting steps, I would appreciate any guidance you can provide. Should I change the constants in the Makefile as per my device or use the default ones?

Sorry I did not find a discussion section so asking my query by creating an issue.

**Comment by ak4zh** [comment]
@dleovl I do not have appropriate skills but from a layman view I don't think crane needs springboard support. May be Crane can support Bootstrap in future if opa releases an update as it should technically only need access to App Data Store and App icon 3D menu access. The new container can be selected from 3D touch menu (clicking on app icon)
Really wish opa get's some free time to have a look and drop some feedback.

**Comment by jailbreakmerebooted** [comment]
@ak4zh you are right. crane doesn't need SBInjection... it is possible

**Comment by dleovl** [comment]
> @dleovl I do not have appropriate skills but from a layman view I don't think crane needs springboard support. May be Crane can support Bootstrap in future if opa releases an update as it should technically only need access to App Data Store and App icon 3D menu access. The new container can be selected from 3D touch menu (clicking on app icon) Really wish opa get's some free time to have a look and drop some feedback.
> 
> Thanks for your tip regarding AppManager I will use it as last resort, Crane just makes the process so much user friendly.

Kinda hard to manage old comments, but Crane starts working once you force close applications before doing anything and set default containers (instead of active). Pretty sure 3d touch menu would need SpringBoard injection, which can happen at any moment now.

**Comment by ak4zh** [comment]
@dleovl When you install an app from App Store, different apps can show different options for the 3d touch options. So that info must be embedded in the IPA itself which should be customisable by the Bootstrap?

**Comment by jailbreakmerebooted** [comment]
@ak4zh the 3D Touch menu can only be tweaked by injecting into SpringBoard other ways are hacky

**Comment by dleovl** [comment]
> @dleovl When you install an app from App Store, different apps can show different options for the 3d touch options. So that info must be embedded in the IPA itself which should be customisable by the Bootstrap?

I'd guess so, but that's extremely tedious and I'm pretty sure you'd need to modify Crane itself to accommodate for the requirements of Crane usage on this bootstrap. My last comment works fine, just follow it and it'll work out tbh
