### ISSUE TITLE
Injecting Apple Music disconnects it from network

### ISSUE THREAD

**Issue by ohvinx** [roothide/Bootstrap#116]
Title
![63C9C64D-5219-4C6F-90D5-115A0E06FE9D](https://github.com/roothide/Bootstrap/assets/96194640/e45e5076-cc4d-4439-a17f-4dcc1c5842a0)
![5C3C19C3-FB4B-41C4-BF69-F645C7C1DFE5](https://github.com/roothide/Bootstrap/assets/96194640/6dc7d8c3-a624-47bb-94f3-1d44538e6529)

**Comment by roothide** [comment]
beta4.2?

**Comment by ohvinx** [comment]
Yes

**Comment by ohvinx** [comment]
![Uploading A1A53B61-C789-4397-92CD-DD700085563D.png…]()

**Comment by ohvinx** [comment]
It seems like it only disconnects it from Wi-Fi because when I open data it works again.

**Comment by ohvinx** [comment]
@roothide @dleovl

**Comment by roothide** [comment]
what is your device region? as far as we know, devices in some regions will restrict the app’s networking permissions.

**Comment by ohvinx** [comment]
It’s Greek. And how does it make sense it only restricts wifi access especially, only when it’s injected💀

**Comment by roothide** [comment]
can you try reinstalling apple musci app?

**Comment by ohvinx** [comment]
Already tried it

**Comment by Pottle** [comment]
I've got this too. really irritating

**Comment by dleovl** [comment]
Seems to be fixed as of [latest release](https://github.com/roothide/Bootstrap/releases). Make a new issue if the error persists.
