### ISSUE TITLE
Stock Apps Crash when Settings Preferences is on from the App Enabler in Bootstrap 4.2

### ISSUE THREAD

**Issue by Faex-an** [roothide/Bootstrap#117]
Stock Apps Crash when Settings Preferences is on from the App Enabler in Bootstrap 4.2

When I open Settings from the bootstrap AppEnabler the Settings app dont open along with all the other stock apps like Mail, Notes, Reminders, Safari etc. 

**iPhone 14 Pro, 16.3.1, Bootstrap Beta 4.2.**

I will share logs for Settings app.
[Settings crash text.txt](https://github.com/roothide/Bootstrap/files/13916160/Settings.crash.text.txt)

**Comment by 0evers** [comment]
Same thing happens on my M1 iPad Pro, but since after installing Seroton, it's fixed.

**Comment by Faex-an** [comment]
> Same issue on my 16.1 M1 iPad Pro, but since installing Serotonin, it works.

I don't even get the Serotonin working bro. Idk why it's the case with me??

**Comment by roothide** [comment]
according to the crash log you provided, it seems to be caused by a broken tweak.

**Comment by dleovl** [comment]
> according to the crash log you provided, it seems to be caused by a broken tweak.

How would you go about determining this conclusion if there's no tweak `.dylib`s in the Binary Images?

**Comment by Faex-an** [comment]
> according to the crash log you provided, it seems to be caused by a broken tweak.

Hi, youre absolutely right. The tweak was _DeleteCut_ . The settings app dont crash anymore. But the tweak Shuffle and TweakSettings do not work for some reason. I am testing some tweaks out one by one. Later i will move to Serotonin. God Willing!

**Comment by roothide** [comment]
> > according to the crash log you provided, it seems to be caused by a broken tweak.
> 
> How would you go about determining this if there's no tweak `.dylib`s in the Binary Images?

the crash log does not show which tweak's dylib it is, but you can see that ellekit's TweakLoader (libinjector.dylib) called dlopen, causing dyld to crash. this is usually caused by a certain tweak's dylib being broken.

**Comment by Faex-an** [comment]
> > > according to the crash log you provided, it seems to be caused by a broken tweak.
> > 
> > 
> > How would you go about determining this if there's no tweak `.dylib`s in the Binary Images?
> 
> the crash log does not show which tweak's dylib it is, but you can see that ellekit's TweakLoader (libinjector.dylib) called dlopen, causing dyld to crash. this is usually caused by a certain tweak's dylib being broken.

I checked one by one and it was deletecut. Thanks a ton dev. instead of shuffle i am using settingsrevamped if anybody wants can use this.
