### ISSUE TITLE
Unable to install enabled apps to Apple Watch

### ISSUE THREAD

**Issue by Jonathan0827** [roothide/Bootstrap#118]
Installing the app from App Store on Apple Watch disables tweak injection to the app

**Comment by dleovl** [comment]
Care to elaborate?
- Which application is this happening with?
- Are you overwriting an injected app? (y/n)
- Does the option for injection disappear? (y/n)
- etc.

**Comment by roothide** [comment]
disable tweak for the app, then install it to apple watch, then enable tweak for the app

**Comment by ArchCangyuan** [comment]
same issue. Originally the app installed from app store runs well on both phone and watch. After enabling injection with bootstrap, the corresponding app on the watch dissappeared. And the app could be installed on the watch after disabling the injection. I tried disabling bluetooth of the phone to make them disconnected, then enabling injection on bootstrap, and the app on the watch worked well after that. But it finally disappeared just after reconnecting them.

**Comment by dleovl** [comment]
If [this comment](https://github.com/roothide/Bootstrap/issues/118#issuecomment-1890953018) does not solve your issue using the latest release, please make a new issue.

**Comment by gzz2000** [comment]
I have the same issue as @ArchCangyuan .
As long as the tweak is enabled for the iOS app, the corresponding watchOS app will be automatically uninstalled once the watch is connected to the phone.

**Comment by roothider** [comment]
reboot device then try this version:
https://cdn.discordapp.com/attachments/1002450165443072041/1289770678911762522/Bootstrap.tipa?ex=66fa080c&is=66f8b68c&hm=95bda1ef34f79af87c4a5ac8a902d613dd2a550a95c7febcae8ae412f0cd9606&
