### ISSUE TITLE
inject dont work

### ISSUE THREAD

**Issue by Suryyartz** [roothide/Bootstrap#119]
After i did install xinamine i tried to add smplinks, it was working but after i delete it i got an error. i didnt took a look on it.
then i went to settings i saw that twaek injeciton stop to work. Treid var clean/ uninstall bootstrap etc, didnt help me to fix it.

**Comment by Suryyartz** [comment]
nvm mind new update fixed it

**Comment by dleovl** [comment]
Xinamine should not be installed on the roothide Bootstrap
