### ISSUE TITLE
After restarting,  Using the injected app 's widget will be blank

### ISSUE THREAD

**Issue by ClaraCora** [roothide/Bootstrap#15]
Using the injected app, after restarting, you need to switch on and off the injection button once to display the content of the widget again, otherwise it will be blank

**Comment by MedewFire** [comment]
If the widget is in the widget page(leftmost page of homescreen) it causes respring

**Comment by dleovl** [comment]
> If the widget is in the widget page(leftmost page of homescreen) it causes respring

The spotlight widgets? If you have a widget there from an injected app it'll cause a respring? When going to that area?

**Comment by MedewFire** [comment]
> > If the widget is in the widget page(leftmost page of homescreen) it causes respring
> 
> The spotlight widgets? If you have a widget there from an injected app it'll cause a respring? When going to that area?

It seems like a Seratonin’s issue, it happens after I jelbrek with Seratonin. And now I can’t reproduce this issue now.
