### ISSUE TITLE
Why is there a lack of testing on iOS 14?

### ISSUE THREAD

**Issue by qichong** [roothide/Bootstrap#188]
As mentioned

**Comment by roothide** [comment]
unsupported yet since there are many jailbreaks for ios14, unless there are developers willing to maintain Bootstrap for ios14

**Comment by hero3210** [comment]
> unsupported yet since there are many jailbreaks for ios14, unless there are developers willing to maintain Bootstrap for ios14

Please consider supporting it. at least for the varClean function. We really need a jailbreak remnants remover before switching to TrollStore.  

On iOS 14.3 (probably all 14.x) Bootstrap crashes upon launch due to the unavailability of
/usr/lib/swift/libswift_Concurrency.dylib

I’m available for testing. 
thanks.

**Comment by dleovl** [comment]
> > unsupported yet since there are many jailbreaks for ios14, unless there are developers willing to maintain Bootstrap for ios14
> 
> Please consider supporting it. at least for the varClean function. We really need a jailbreak remnants remover before switching to TrollStore.
> 
> On iOS 14.3 (probably all 14.x) Bootstrap crashes upon launch due to the unavailability of /usr/lib/swift/libswift_Concurrency.dylib
> 
> I’m available for testing. thanks.

If you have an iOS 15+ TrollStore device, you could ***maybe*** try repacking the `.app` directory of the Manager app into an `.ipa` and installing it on iOS 14, though I'm not sure how far that would get you.

Considering the Manager app is outside the scope of the repository, your request is most likely suited for [roothide/RootHideManagerApp](https://github.com/roothide/RootHideManagerApp).

There are rules the application follows to determine what files or directories should be listed for removal; maybe try manually testing items against these rules? Check out [VarCleanRules.json](https://github.com/roothide/RootHideManagerApp/blob/main/RootHide/VarCleanRules.json) for what the application considers to be a part of a jailbroken environment.

**Comment by hero3210** [comment]
> Considering the Manager app is outside the scope of the repository, your request is most likely suited for [roothide/RootHideManagerApp](https://github.com/roothide/RootHideManagerApp).
>

Thanks so much for the informative reply. But my request is mainly to fix the iOS 14 support since the README states that iOS 14 is supported.

**Comment by ip146** [comment]
I hope ios14 will be supported, because un and taurine jailbreak will make some machines unable to make normal calls.

**Comment by ip146** [comment]
It seems that ios14 is not supported
