### ISSUE TITLE
Libcolorpicker

### ISSUE THREAD

**Issue by GreatNateDev** [roothide/Bootstrap#197]
Converting breaks it

**Comment by dleovl** [comment]
> Converting breaks it 

Can you name a tweak that utilizes it? `org.thebigboss.libcolorpicker`, yes?

**Comment by GreatNateDev** [comment]
![Uploading IMG_2788.jpeg…]()

**Comment by GreatNateDev** [comment]
It’s the one by spark dev

**Comment by GreatNateDev** [comment]
Needed for a lot of his packages

**Comment by GreatNateDev** [comment]
Btw using serotonin jailbreak with bootstrap iOS 16.5 on iPad 8th gen wifi

**Comment by GreatNateDev** [comment]
Seems to be a zebra issue Sileo worked fine marking as resolved
