### ISSUE TITLE
Neither Fix App Notification nor disabling/enabling injection enables notifications

### ISSUE THREAD

**Issue by Suryyartz** [roothide/Bootstrap#210]
I did build my own bootstrap, using github but for some reason the button show me done but doesn’t fix the notification.
![IMG_4605](https://github.com/roothide/Bootstrap/assets/46917227/bc74fa8b-3809-4de6-8df0-c5924a65e788)

**Comment by dleovl** [comment]
This user has also reported that disabling and enabling injection into an application (manual) still does not provide notifications.

Badges for notifications come through, though this has been the same since public release.

#2

**Comment by roothide** [comment]
what app?  and you need to reboot the device and re-bootstrap to test

**Comment by Suryyartz** [comment]
Youtube, insta and whatsapp

**Comment by Suryyartz** [comment]
Well i did rebooted when i did updated the bootstrap

**Comment by jedai47** [comment]
Same issue here. Specially for whatsapp

**Comment by dleovl** [comment]
> Same issue here. Specially for whatsapp

Are you using the latest Bootstrap version, and is WhatsApp installed from the App Store?

**Comment by dleovl** [comment]
Notifications are automatically enabled as per the [latest release](https://github.com/roothide/Bootstrap/releases).
