### ISSUE TITLE
Asseration failed in jbroot.c

### ISSUE THREAD

**Issue by baW01** [roothide/Bootstrap#211]
ios-version: 16.7.4
device-model: iPhone 10,4
app-version: 1.0

faild(134):
ERR:Asseration failed:
(stat(JBROOT, &jbrootst) == 0), function__private_jbrootat_alloc,
file jbroot.c, line 38.

***exception: Bootstrap.m (220)

**Comment by roothider** [comment]
can you upload crash file? (*.ips)

**Comment by baW01** [comment]
Version 1.1.1 solve the problem

W dniu niedz., 4.02.2024 o 18:50 roothider ***@***.***>
napisał(a):
