### ISSUE TITLE
Settings app and imessage crash upon open

### ISSUE THREAD

**Issue by YtFanboiiiExe** [roothide/Bootstrap#223]
### Device Model

iPhone 11, a13

### iOS Version

15.6.1

### Bootstrap Version

1.1

### What happened?

As said in the name, settings and imessage crash. They worked perfectly with tweaks on bootstrap 1.0…

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Any logs?
