### ISSUE TITLE
Serotonin app vs Bluetooth

### ISSUE THREAD

**Issue by le21gars** [roothide/Bootstrap#224]
### Device Model

IPhone 13 mini

### iOS Version

iOS 16.6.b1

### Bootstrap Version

1.1

### Serotonin Version

1.2.1

### What happened?

I installed Bootstrap - Ellekit - Serotonin.
Serotonin crashes on opening and returns to the home page. After several tries between installation and reinstallation of the whole thing. I have to disable my Bluetooth and Serotonin
works. This is the method that works for me. I don't know if it's because I'm using an external keyboard and mouse. Nothing else is connected. I don't know if it's a bug generated by Bootstrap or a conflict with Bluetooth after installing bootstrap. I read on Discord another person having the same problem as me.

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by Mukul1127** [comment]
This issue should probably be on the serotonin github

**Comment by dleovl** [comment]
Hey, this issue is probably more suited for `mineek/Serotonin`. Best of luck to you!
