### ISSUE TITLE
Control Centre Music Recognition does not work once device is Bootstrapped 

### ISSUE THREAD

**Issue by wonkieinc** [roothide/Bootstrap#226]
### Device Model

iPhone 13 Pro

### iOS Version

16.1.2

### Bootstrap Version

1.1

### Serotonin Version

1.2.0

### What happened?

When I reboot my phone to a totally stock state, CC Music Recognition works as usual and can identify music playing on the device 

When I Bootstrap and run Userspace Reboot, and test again, all songs give ‘No Result, We we’re unable to find anything’ 

Note, this problem begins before opening and running Serotonin, after just running the Bootstrap. This happened on 1.0 as well. 

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by wonkieinc** [comment]
I’ve just tested rebooting and Bootstrapping with the ‘Tweak Enable’ switch off, and this issue is not present in this statw

**Comment by roothider** [comment]
> I’ve just tested rebooting and Bootstrapping with the ‘Tweak Enable’ switch off, and this issue is not present in this state

rebuild icon cache in settings of Bootstrap
