### ISSUE TITLE
Injecting into com.apple.Spotlight does not work. Spotlight fails to launch

### ISSUE THREAD

**Issue by p2kdev** [roothide/Bootstrap#228]
### Device Model

iPhone 14 Pro

### iOS Version

16.5.1

### Bootstrap Version

1.1

### Serotonin Version

1.2.1

### What happened?

When spotlight (com.apple.Spotlight) is enabled from the applist for tweak injection, the spotlight doesn't load. 

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Hey p2k! Love your work. Marking this as confirmed, can vouch it breaks Spotlight on iOS 17 as well.

**Comment by phoen1x74** [comment]
still present in 1.1.1, iphone 14 on 16.6 beta 1

**Comment by roothider** [comment]
will be fixed in next version

**Comment by phoen1x74** [comment]
latest commits did not fix for me, iphone 14 16.6 beta built from source

**Comment by p2kdev** [comment]
It works for me. Tweaks are working in spotlight. I tried thr build posted on discord

**Comment by phoen1x74** [comment]
> It works for me. Tweaks are working in spotlight. I tried thr build posted on discord

link to msg pls :-p

**Comment by phoen1x74** [comment]
found it, even with that build spotlight is still broken with injection for me :-(

**Comment by phoen1x74** [comment]
still broke on 1.2.1 for me :p

**Comment by roothider** [comment]
> still broke on 1.2.1 for me :p

any crash logs in /var/mobile/Library/CrashReporter/ ?

**Comment by roothider** [comment]
and try "disable tweak" then "enable tweak" for spotlight

**Comment by roothider** [comment]
> still broke on 1.2.1 for me :p

crashed by this tweak 
<img width="715" alt="image" src="https://github.com/roothide/Bootstrap/assets/158083651/71799285-de17-4781-9de7-e5ee1ba5c080">
