### ISSUE TITLE
[Injection] com.apple.mobilemail breaks account inboxes

### ISSUE THREAD

**Issue by dleovl** [roothide/Bootstrap#231]
### What happened?

Injection into `com.apple.mobilemail` causes account specific inbox buttons to disappear under their corresponding email address labels.

### How to reproduce:

Take note of the inboxes (Drafts, Sent, Junk, Trash) for any given account, and notice they disappear upon injecting, leaving only 'Inbox' for each account. This also moves iCloud (a priority at the top) down the account list.

**Comment by roothider** [comment]
will be fixed in next version

**Comment by dleovl** [comment]
Fixed as of 1.2.1. Uninject, (try refreshing icon cache?), and reinject.
