### ISSUE TITLE
Error: you have installed an old beta version, (after updating)

### ISSUE THREAD

**Issue by trashthrows** [roothide/Bootstrap#236]
### Device Model

iPhone 14

### iOS Version

17.0

### Bootstrap Version

1.1

### What happened?

I updated the app from beta 2 to 1.1 by installing through trollstore (did not delete app beforehand), and I was made to reboot my phone after opening the updated version. Now this error appears telling me to disable all app tweaks and reboot to install new version. I do not have access to app selector to disable tweaks and this error appears every time, what do I do

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
This is more suited for the roothide Discord server. Completely uninstall your bootstrap after a reboot (read the FAQ) and reinstall, making sure to uninject/reinject applications you previously had injected (check for presence of appbackup directories).
