### ISSUE TITLE
WeChat microphone activation unsuccessful

### ISSUE THREAD

**Issue by waitfq** [roothide/Bootstrap#238]
### Device Model

iPhone13 pro

### iOS Version

16.1

### Bootstrap Version

1.1

### What happened?

WeChat microphone activation unsuccessful

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by roothider** [comment]
Is there any way to exactly reproduce this issue?

**Comment by Tiberiusjhh** [comment]
有修复时间么？

**Comment by dleovl** [comment]
If this issue persists as of the latest Bootstrap version, please make a new issue with more information on how to reproduce this bug.
