### ISSUE TITLE
AppStore not loading images

### ISSUE THREAD

**Issue by ricosuave0922** [roothide/Bootstrap#244]
### Device Model

iPhone 14 Pro Max

### iOS Version

16.5

### Bootstrap Version

1.1.1

### Serotonin Version

1.2.0

### What happened

Since updating bootstrap to 1.1.1 the AppStore app no longer loads images for anything while the device is bootstrapped. If I reboot it works fine.
![IMG_1269](https://github.com/roothide/Bootstrap/assets/2651533/03b3ff9c-fedf-4df8-92ec-ed0845be5504)

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Fine on my end, though I'm not using Serotonin. Can you verify this issue doesn't happen when you're bootstrapped without Serotonin enabled?

**Comment by ricosuave0922** [comment]
I can try. I have tried uninstalling bootstrap and installing an older version, but the problem persists. On my phone that has used serotonin, if I reboot App Store loads fine. If I bootstrap it stops loading correctly. If I serotonin and then reboot bootstrap server is still doesn’t work.

**Comment by dleovl** [comment]
Do you have the App Store injected? Uninject the App Store, and reopen the App Store while bootstrapped (Serotonin disabled) and tell me the results.

**Comment by ricosuave0922** [comment]
That was my first thought too. I tried disabling injection for it but it still occurs.

**Comment by roothider** [comment]
> That was my first thought too. I tried disabling injection for it but it still occurs.

"rebuild icon cache" in settings of Boostrap

**Comment by ricosuave0922** [comment]
Tried both the rebuild icon cache and rebuild apps, neither fixed it

**Comment by roothider** [comment]
> Tried both the rebuild icon cache and rebuild apps, neither fixed it

disable tweak for the app and then rebuild icon cache in Boostrap, if the problem is still not solved, it is most likely not caused by Bootstrap.

**Comment by ricosuave0922** [comment]
That seems to have done the trick finally. Not sure why it didn’t fox it before but today it did.
