### ISSUE TITLE
disable tweak for app, the app icon moves from inside the file to outside the folder

### ISSUE THREAD

**Issue by YGQ8988** [roothide/Bootstrap#248]
### Device Model

iPhone 12PM A14

### iOS Version

16.6.1

### Bootstrap Version

1.2.1

### Serotonin Version

1.2.1

### What happened

When I disable tweak for app, the app icon moves from inside the file to outside the folder

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by roothider** [comment]
known issue, not a real problem

**Comment by dleovl** [comment]
Not going to be fixed, as this is just a side effect of how injection works.
