### ISSUE TITLE
iOS 15.6 iPhone 12 Stock Apps crash

### ISSUE THREAD

**Issue by pwnmaphone** [RootHide/Bootstrap#25]
Whenever I try to inject tweaks into Music/Settings the app will crash at start i've tried restarting rebuilding apps in both bootstrap and in trollstore to no avail.

**Comment by dleovl** [comment]
Mentioned by two users, other on 16.1.2. Have not seen any known conflicting tweaks for com.apple.Preferences in tweaklist.

**Comment by RootHide** [comment]
try beta2,  if still not work.  zip all files in /var/mobile/Library/Logs/CrashReporter  and upload

**Comment by pwnmaphone** [comment]
[CrashReporter.zip](https://github.com/RootHide/Bootstrap/files/13801536/CrashReporter.zip)

**Comment by pwnmaphone** [comment]
beta 2 didnt work those are my crash logs

**Comment by pwnmaphone** [comment]
tweaks for music: artfull for settings: cask3

**Comment by dleovl** [comment]
> for settings: cask3

Check the pins in #bootstrap in the Discord (link in README)

**Comment by zvxfdev** [comment]
I notice that Settings only crashes for me when opened after searching for it. If I launch it through the home screen, it works fine.
