### ISSUE TITLE
I can’t install Bootstrap.

### ISSUE THREAD

**Issue by tnt0x** [roothide/Bootstrap#255]
### Device Model

iPad 10

### iOS Version

17.4

### Bootstrap Version

All

### Serotonin Version

1.2.@

### What happened

I want to install Bootstrap, I didn’t installed TrollStore. So I renamed this installation package to "Bootstrap.ipa"then signed with the signature software GBox and there is no problem with the certificate.But the system cannot verify the integrity.

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by tnt0x** [comment]
I can install Serotonin and Minecraft and I use the same certificate and software.

**Comment by dleovl** [comment]
Neither Bootstrap nor Serotonin support iOS versions past 17.0.
