### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by nahtedetihw** [roothide/Bootstrap#257]
### Device Model

iPhone 14 Pro Max

### iOS Version

16.1

### Bootstrap Version

1.2.1

### Serotonin Version

n/a

### What happened

Upon uninstall, the selected apps are not deactivated. This causes apps to be removed from CarPlay.

### Log output

```shell
n/a
```

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Read the FAQ on how to properly uninstall next time.

**Comment by nahtedetihw** [comment]
Or it could be properly fixed to revert these changes upon uninstalling so more users are not having the same issue.On Feb 18, 2024, at 4:46 AM, dleovl ***@***.***> wrote:﻿
Read the FAQ on how to properly uninstall next time.

**Comment by dleovl** [comment]
pretty sure it warns you 🤷

**Comment by nahtedetihw** [comment]
That is incorrect.On Feb 18, 2024, at 2:14 PM, dleovl ***@***.***> wrote:﻿
pretty sure it warns you 🤷

**Comment by ojpifdsaew** [comment]
> That is incorrect.On Feb 18, 2024, at 2:14 PM, dleovl ***@***.***> wrote:﻿ pretty sure it warns you 🤷 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

it does warn you. you havent paid attention while uninstalling.
