### ISSUE TITLE
It will destroy map app 

### ISSUE THREAD

**Issue by Uni9k** [roothide/Bootstrap#259]
### Device Model

iPhone 14 PM

### iOS Version

17.0

### Bootstrap Version

1.2.1

### Serotonin Version

none

### What happened

My map app will prompt for abnormal satellite positioning signals.and it will get stuck and not move.
this problem arises whether or not I inject map app.
![Uploading 微信图片_20240222155114.png…]()

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Can you upload the photo again? Also, which app is affected?

**Comment by Uni9k** [comment]
@dleovl

**Comment by dleovl** [comment]
Hi, are you still encountering this issue?
