### ISSUE TITLE
RootHide Manager and Choicy not working

### ISSUE THREAD

**Issue by jonahdecker** [roothide/Bootstrap#262]
### Device Model

iPhone 13, A15

### iOS Version

17.0

### Bootstrap Version

1.2.1

### What happened

Tried installing Choicy and RootHide Manager from the official RootHide repository. Both of them are not working for me. 

Choicy has a problem with the preferences. Specifically, `ChoicyPrefs.bundle`. 
![IMG_3618](https://github.com/roothide/Bootstrap/assets/54655460/b229b01f-0897-41c3-a172-4ef13627dc5e)
![IMG_3619](https://github.com/roothide/Bootstrap/assets/54655460/8e5f9474-4e08-4490-b436-eb59b5b5417d)
![IMG_3620](https://github.com/roothide/Bootstrap/assets/54655460/c58c4d01-4dad-4d20-8b15-107bfc8054a1)

RootHide Manager installs, but crashes when I try to open it. 

https://github.com/roothide/Bootstrap/assets/54655460/16c4f798-f632-4122-be8f-c367452a3bec

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by dleovl** [comment]
Odd, looks like thinks aren't going too well. Does reinstalling the tweaks not fix it? If that doesn't work, you can try uninstalling the Bootstrap (according to the FAQ in this GitHub's `README.md` and reinstalling the bootstrap. You can export your source and tweak list to make things easier.

**Comment by roothider** [comment]
try to reinstall the packages

**Comment by dleovl** [comment]
As this issue is not easily reproducible, this issue will be closed.

It should be noted that you should steer clear from repositories that host pirated content. Pirated content involves content that may either,
1. Redistribute content without the owners explicit permission, or do not abide by licensing, or
2. Provide paid content for free

**Comment by dleovl** [comment]
No, these tweaks work fine on 17.0.
