### ISSUE TITLE
can’t install

### ISSUE THREAD

**Issue by logicapples** [roothide/Bootstrap#264]
### Device Model

iPhone X

### iOS Version

16.7.6 RC

### Bootstrap Version

0

### What happened

In description it says it supports ios 14.0-17.0 but when I sideload ipa and click bootstrap it gives me error that trollstore is outdated. Please help fix this

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by logicapples** [comment]
> This application must be installed with TrollStore; no alternatives.

Then the readme is deceiving since it will never work on 16.7

**Comment by dleovl** [comment]
> > This application must be installed with TrollStore; no alternatives.
> 
> Then the readme is deceiving since it will never work on 16.7

Not quite. https://github.com/roothide/Bootstrap#usage

**Comment by logicapples** [comment]
> > > This application must be installed with TrollStore; no alternatives.
> > 
> > 
> > Then the readme is deceiving since it will never work on 16.7
> 
> Not quite. https://github.com/roothide/Bootstrap#usage

![IMG_0240](https://github.com/roothide/Bootstrap/assets/76408169/7220514f-d7a2-4d5c-9318-b56c91cb558a)

**Comment by dleovl** [comment]
TrollStore is a requirement, as stated in usage. That line of information isn't wrong, albeit could be clarified. Try it with palera1n's TrollStore and tell me how far you get.
