### ISSUE TITLE
works great on iphone 7 iOS 15.8.2 but

### ISSUE THREAD

**Issue by cuneytsezer** [roothide/Bootstrap#268]
iphone 7 works great on iOS 15.8.2, but if arm64 support is added, it will be legendary, this is the most stable jailbreak right now. Only some tweaks do not work.

**Comment by cuneytsezer** [comment]
Please know that no jailbreak works as stable as this one. It has been a life saver for my iphone 7 and works perfectly. If Arm64 support is added, it will be legendary.

**Comment by dleovl** [comment]
This is ***not***a jailbreak, and arm64 (device architecture pre-A12) is already supported starting with A8. If you're looking for an ***iphoneos-arm64*** bootstrap, sorry, but that's not what this repository is for. Someone will either need to fork this repository and change EVERYTHING to be rootless or simply make their own from scratch. Throw together a Procursus basebin, do some CoreTrust bypass magic, and voila.

**Comment by cuneytsezer** [comment]
Thank you very much for the information, I know that this is not jailbreak and my iphone 7 works very well. I don't need jailbreak because whatever jailbreak I have tried, it breaks my device. This application works very well in patching, the only problem is that tweaks like Filza, charge limiter, audio Recorder xs do not work. Everything else works very well, very stable.
