### ISSUE TITLE
Appsync cannot be installed/Missing firmware?

### ISSUE THREAD

**Issue by jakeywkey** [roothide/Bootstrap#284]
### Device Model

Ipad 9th gen A13 Bionic Chip 

### iOS Version

16.6

### Bootstrap Version

1.2.8

### Serotonin Version

1.2.1

### What happened

![IMG_0280](https://github.com/user-attachments/assets/858291e4-005f-4cd7-8ba3-212aeac2dafa)
Cant download app sync 

### Log output

```shell
Depends Firmware
```

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by imnltsa** [comment]
AppSync isn't supported on your version. Install `.ipa` files through TrollStore.
