### ISSUE TITLE
I can't build bootstrap

### ISSUE THREAD

**Issue by wheelchairy** [roothide/Bootstrap#285]
**I get this error:**

`/Users/wheelchairy/theos/makefiles/common.mk:128: *** 'roothide' package scheme does not exist.  Stop.`

How to fix this error?

**Comment by imnltsa** [comment]
Do you have [roothide Theos](https://github.com/roothide/Bootstrap#building)?

**Comment by wheelchairy** [comment]
> Do you have [roothide Theos](https://github.com/roothide/Bootstrap#building)?

Yes

**Comment by wheelchairy** [comment]
I just reinstalled theos and everything worked!
