### ISSUE TITLE
Deletes already active jailbreak

### ISSUE THREAD

**Issue by erzurum2525** [roothide/Bootstrap#286]
### Device Model

iPad 7, A10

### iOS Version

17.7

### Bootstrap Version

latest

### Serotonin Version

Palera1n

### What happened

I installed the app through TrollStore Lite so I can get roothide jailbreak which would allow me to bypass jailbreak detection, but instead I got "error (255)" And had to completely erase my jailbreak and jailbreak again.

### Acknowledgement of README and FAQ

- [X] I have read both the README and the FAQ.

**Comment by roothider** [comment]
1: Bootstrap may not support Trollstore Lite
2: roothide can not help you to hide palera1n

**Comment by imnltsa** [comment]
Unsupported

**Comment by erzurum2525** [comment]
Why does it delete already active jailbreak? it being unsupported is fine, but deleting jailbreak is insane

**Comment by erzurum2525** [comment]
Also trollstore lite is basically the same as trollstore, but trollstore is only for jailbroken users
