### ISSUE TITLE
Orion Runtime Refuses to install on ios 17

### ISSUE THREAD

**Issue by AirrickD** [RootHide/Bootstrap#29]
Both sileo and zebra throw a "depends firmware" error when trying to install Orion on ios 17.  I'm using the version from the root hide repo. (Only on ios 17, on ios 16 it installs.)

**Comment by dleovl** [comment]
The tweak (dev.theos.orion14) itself will need to be updated, this is outside the scope of the bootstrap. Maybe an issue for https://github.com/RootHide/theos or it's parent repository https://github.com/theos/theos

**Comment by dleovl** [comment]
dev.theos.orion14 has been fixed for iOS 17.0 on the https://roothide.github.io/ repository.
