### ISSUE TITLE
Cask 3 settings do not save

### ISSUE THREAD

**Issue by Dreel0akl** [roothide/Bootstrap#3]
Hey there, I’m trying to use the bootstrap with the “Cask 3” tweak but it seems like changing the settings for this tweak refuse to save.

**Comment by dleovl** [comment]
You can find a working .deb file in the RootHide Discord server, it's confirmed to work.

**Comment by dleovl** [comment]
Closing, as its outside the scope of this repository. The tweak will need to be patched (and has) or properly updated to support new paths.
