### ISSUE TITLE
Cannot place calls while com.apple.InCallService is enabled in App List

### ISSUE THREAD

**Issue by Migaas001** [roothide/Bootstrap#32]
I have some tweaks installed and working, when I active InCallService on bootstrap, I can’t make calls with the phone app.
I was trying AudioRecorder, I thought that was the problem but I uninstalled it and the issue persist, so I de activate InCallService on bootstrap, and know works.

Can I inject tweaks on InCallService?

**Comment by dleovl** [comment]
> some tweaks have to update for ios16 A12+

Seems like injection into com.apple.InCallService breaks making calls from the Phone app from starting.

**Comment by RootHide** [comment]
> > some tweaks have to update for ios16 A12+
> 
> Seems like injection into com.apple.InCallService breaks making calls from the Phone app from starting.

maybe crash by some tweak,  any crash log?

**Comment by Migaas001** [comment]
> > > some tweaks have to update for ios16 A12+
> > 
> > 
> > Seems like injection into com.apple.InCallService breaks making calls from the Phone app from starting.
> 
> maybe crash by some tweak, any crash log?

I add a krashlog in the link below

https://drive.google.com/drive/folders/1cCvCxXS4gZU0u960PQZDrxoRPmRPoBAc

thanks

**Comment by dleovl** [comment]
> > > some tweaks have to update for ios16 A12+
> 
> > 
> 
> > Seems like injection into com.apple.InCallService breaks making calls from the Phone app from starting.
> 
> 
> 
> maybe crash by some tweak,  any crash log?

Don't have any tweaks that would modify it

**Comment by dleovl** [comment]
> > > > some tweaks have to update for ios16 A12+
> > > 
> > > 
> > > Seems like injection into com.apple.InCallService breaks making calls from the Phone app from starting.
> > 
> > 
> > maybe crash by some tweak, any crash log?
> 
> I add a krashlog in the link below
> 
> https://drive.google.com/drive/folders/1cCvCxXS4gZU0u960PQZDrxoRPmRPoBAc
> 
> thanks

Doesn't look like any tweaks are messing with it, only one that concerns me is 'SpringBoardHome'
