### ISSUE TITLE
com.apple.shortcuts crashes on launch when enabled in App List

### ISSUE THREAD

**Issue by theoccurrence** [roothide/Bootstrap#35]
Title. Disabling it makes it work again.

**Comment by dleovl** [comment]
Confirmed not working on 17.0 A13

**Comment by RootHide** [comment]
bug confirmed

**Comment by RootHide** [comment]
will fix in next beta version

**Comment by dleovl** [comment]
Fixed as of [latest release](https://github.com/roothide/Bootstrap/releases).
