### ISSUE TITLE
Unable to uninstall on iPhone 7

### ISSUE THREAD

**Issue by EEEEtoin** [RootHide/Bootstrap#36]
The uninstall button is offscreen and there is no way to scroll down.

**Comment by TweaksDev22** [comment]
First remove all select apps from option app enabler then You need rebooted device then uninstall

**Comment by dleovl** [comment]
Like what @TweaksDev22 said, disable everything in AppEnabler, reboot, then you can uninstall. Please refer to the FAQ posted in the Discord (linked in README) for future assistance. Thanks for using RootHide Bootstrap.

**Comment by dleovl** [comment]
The bootstrap UI will eventually be updated, if your issue persists please hold out until then.
