### ISSUE TITLE
Inconsistent crashes in com.apple.Preferences

### ISSUE THREAD

**Issue by dleovl** [RootHide/Bootstrap#37]
Stated in the Discord, some people are experiencing crashes related to com.apple.Preferences when installing PreferenceLoader. TweakSettings by CreatureSurvive can be used as an alternative for these people, but it's good to address the issue directly. Even on clean Bootstrap installs, some people are unable to use Settings as a tweak preference changer, and must rely on TweakSettings, while some people are the complete opposite, with both working for some people.

**Comment by TweaksDev22** [comment]
@dleovl i suggest to using Rebuild chache app in TrollStore..

**Comment by dleovl** [comment]
> @dleovl i suggest to using Rebuild chache app in TrollStore..

I don't have this issue personally. I know how to fix icon cache, it's just PreferenceLoader breaks com.apple.Preferences for some people and they're forced to result to other ways to edit preferences instead of PreferenceLoader. This is a valid issue.

**Comment by RootHide** [comment]
any crash log about "Preference"?

**Comment by dleovl** [comment]
Will keep issue updated

**Comment by dleovl** [comment]
An influx of people are going to install Flex 3 Beta by John Coates due to it being widespread advertised again, but this is one confirmed tweak that does break com.apple.Preferences.

One log by Discord user 548446288060874770: [log.txt](https://github.com/RootHide/Bootstrap/files/13830335/log.txt)

Will do more testing to see if it's really closely related to PreferenceLoader.

**Comment by dleovl** [comment]
Upon further investigation, it was Flex 3 Beta by John Coates that caused the crashes, and it has been updated to work alongside PreferenceLoader.
