### ISSUE TITLE
Bootstrap Beta 2 - Developer Mode Issue!

### ISSUE THREAD

**Issue by AhmedAlNeaimy** [RootHide/Bootstrap#38]
After extracted the iPA file from the source code, and installed the Bootstrap using TrollStore2, i'm still not able to JB my iPhone because the app doesn't check the Developer Mode is already Enabled correctly 

Info:
iPhone XS Max, iOS 16.4.1

![IMG_4760](https://github.com/RootHide/Bootstrap/assets/16979870/c5fb08a4-ddc4-434b-a2ba-c34a70190598)
![IMG_4761](https://github.com/RootHide/Bootstrap/assets/16979870/7afac475-2a0a-4abd-bb34-1167243db8b5)

**Comment by TweaksDev22** [comment]
@AhmedAlNeaimy  i think you build  the  beta 2 by wrong its should working  prefect without issues also when showing those errors when trying to install Bootstrap thats mean  you build the Bootstrap by wrong  try rebuild it ..

**Comment by dleovl** [comment]
@AhmedAlNeaimy Have you been able to fix this issue with the latest beta?

**Comment by AhmedAlNeaimy** [comment]
> @AhmedAlNeaimy i think you build the beta 2 by wrong its should working prefect without issues also when showing those errors when trying to install Bootstrap thats mean you build the Bootstrap by wrong try rebuild it ..

You're right,
i didn't followed your build steps because it's not clear so i read it again and everything if perfect.

**Comment by AhmedAlNeaimy** [comment]
> @AhmedAlNeaimy Have you been able to fix this issue with the latest beta?

Yes, since Beta 2 everything works perfectly.
