### ISSUE TITLE
Offloading apps

### ISSUE THREAD

**Issue by nikc88** [roothide/Bootstrap#41]
Constant offloading of any apps that are enabled through bootstrap, sometimes to the point the apps are unusable.

**Comment by dleovl** [comment]
Are you sure they're offloaded (they'll get a cloud icon next to them), or just disappearing from the homescreen completely due to icon cache?

I can say, this did result in my keyboard app being offloaded. Not entirely sure why lol

**Comment by dleovl** [comment]
> The only apps I've had completely disappear were Facebook and messenger, but the other apps I that I have enabled with bootstrap just offload at random times

Can confirm the offloading. For Facebook and Messenger, try to rebuild apps in the Bootstrap application.

**Comment by dleovl** [comment]
If this issue persists with the latest commits, please make a new issue.

Personally, the offloading died down.
