### ISSUE TITLE
Jailbreak Detection Megaissue

### ISSUE THREAD

**Issue by dleovl** [roothide/Bootstrap#48]
This issue can be used to list off apps that have jailbreak detection _advanced_ enough to detect **_WITHOUT_** injection with AppEnabler or even after uninstalling the bootstrap and removing `/private/var/jb` and `/private/var/containers/Bundle/Application/.jbroot-$(jbrand)/` along with application data removal.

It's not necessarily helpful to link to tweaks which may bypass anything in here since this is an issue on the Bootstrap repo itself, but can narrow it down.

_Before commenting, please ensure you 100% do not have anything visible like Filza's URL scheme (Remove Filza from TrollStore and install the [no URL scheme version](https://tigisoftware.com/download/Filza_NoURLScheme_4.0.0.ipa)) and any other jailbreak application that may expose their URL scheme. Also, ensure your results aren't stored anywhere by clearing application data by uninstalling and reinstalling the application, assuming the results are stored there._

**Comment by xyndicategaming** [comment]
Fix issue with Roothide manager clean/var

**Comment by dleovl** [comment]
> Fix issue with Roothide manager clean/var

This doesn't address the issue at hand; the problem still exists with RootHide as a hole. Removing files doesn't fix the fact that there's something wrong with the bootstraps anti-jb detection.

Plus, this is an issue for ALL apps that have jailbreak detection, you need somewhere to complain about it.

Running varClean with 'select all' could be a fix for people ditching the bootstrap, but certainly not one that wants to keep using it.

**Comment by RootHide** [comment]
follow this:

1: enable tweak for all trollstore apps

2: install roothide manager in sileo,  try varClean all in roothide manager, some files may not be deleted automatically and you need to do it manually in filza.

**Comment by dleovl** [comment]
> follow this:
> 
> 1: enable tweak for all trollstore apps
> 
> 2: install roothide manager in sileo, try varClean all in roothide manager, some files may not be deleted automatically and you need to do it manually in filza.

How does this affect people who want to still use the bootstrap? This is fine for people leaving the bootstrap but deletes pretty important stuff if you want to continue using it.

**Comment by RootHide** [comment]
> > follow this:
> > 1: enable tweak for all trollstore apps
> > 2: install roothide manager in sileo, try varClean all in roothide manager, some files may not be deleted automatically and you need to do it manually in filza.
> 
> How does this affect people who want to still use the bootstrap? This is fine for people leaving the bootstrap but deletes pretty important stuff if you want to continue using it.



1: Some users have installed other bootstrap with /var/jb before, and it is very easy to detect.

2: Some apps installed in the trollstore may be detected as jailbroken, not just because of URLSchemes. after enabling tweaks for them, Bootstrap will automatically hide some features for them.

3: Some tweaks and jailbreak apps (including apps installed in the trollstore) will generate some files in /var/ of the rootfs, which will also be used by the app to detect jailbreaks. they can be cleaned using roothide manager's varClean, and we strongly recommend tweaks and jailbreak apps should store their data and configuration in jbroot's /var/ rather than rootfs's /var/.

**Comment by xyndicategaming** [comment]
Yes like the RoothideDev said , the Roothide manager is solution , or use filza or other jb apps with no url scheme instead

**Comment by dleovl** [comment]
> > > follow this:
> > > 1: enable tweak for all trollstore apps
> > > 2: install roothide manager in sileo, try varClean all in roothide manager, some files may not be deleted automatically and you need to do it manually in filza.
> > 
> > 
> > How does this affect people who want to still use the bootstrap? This is fine for people leaving the bootstrap but deletes pretty important stuff if you want to continue using it.
> 
> 1: Some users have installed other bootstrap with /var/jb before, and it is very easy to detect.
> 
> 2: Some apps installed in the trollstore may be detected as jailbroken, not just because of URLSchemes. after enabling tweaks for them, Bootstrap will automatically hide some features for them.
> 
> 3: Some tweaks and jailbreak apps (including apps installed in the trollstore) will generate some files in /var/ of the rootfs, which will also be used by the app to detect jailbreaks. they can be cleaned using roothide manager's varClean, and we strongly recommend tweaks and jailbreak apps should store their data and configuration in jbroot's /var/ rather than rootfs's /var/.

What can people do to mitigate detection without doing a full varClean (data loss, i know a loss of preference bundles is guaranteed, along with files from TrollStore applications like Derootifier or misaka)? Yes, you should wipe previous jailbreak files, but you can't necessarily tell which files are used in the current bootstrap or utilized by your TrollStore apps.

**Comment by roothide** [comment]
whether it is a tweak or a trollstore app/jailbreak app, data and configuration should be stored in the sandbox container or jbroot:/var/, not rootfs:/var/.

the roothide manager can help users find files stored in rootfs:/var/ that may lead to the detection of jailbreak. once the future tweaks store data and configuration in the sandbox container or jbroot:/var/, then we can get rid of this is a legacy issue from history, but it will take time.

In rootihde jailbreak (such as roothide dopamine), the tweak preferences will be automatically redirected to jbroot for storage by cfprefsd-hook, but in Bootstrap we are not able to achieve this yet.

**Comment by Kawaoii** [comment]
Question. Idk if I ask this here. If I have a phone without JB but only ts. And want to install and use roothide bootstrap for sileo can banking/gov apps detect this process and/or are there steps to avoid this issue?

**Comment by roothide** [comment]
> Question. Idk if I ask this here. If I have a phone without JB but only ts. And want to install and use roothide bootstrap for sileo can banking/gov apps detect this process and/or are there steps to avoid this issue? Essentially what I want to know is if roothide bootstrap can be detected as JB.

any behavior beyond the scope allowed by apple may be detected as a jailbreak, including trollstore.

even if you only use a developer certificate to sideload some apps (such as filza), some appstore apps may report that your device is jailbroken.

the significance of roothide is that it provides a universal solution to these troubles.

**Comment by uphantom89** [comment]
One app detect my phone as jailbroken.
App name: Lookout for work
App function: check phone jailbroken status,, if passed , it let me use other Microsoft app : teams, outlook…(with company account)

My device: xs max
Ios:17.0 with Trollstore
App installed with TS: uYoyplus, Spotify, anki, facebook
Bootstrap: installed beta 2 —> uninstalled, installed beta 4.2 
What I hav tried: follow faq instructions: install Roothide manager, remove all selected file, uninstall bootstrap  (tried with both scenarios : “lookout for work” on the phone and be removed)

Result: App still detected my phone as jailbroken

**Comment by MysticallyQ8** [comment]
Hello, i have recently encountered my banking app that detect my JB, iphone 14 pro max ios 16.6.1, i have been using the app without no bypass tweaks and it was fine for almost 2 weeks until yesterday it detected as My device is unsecured Bc of jailbreak. I followed the uninstallation method from A to Z and yet i still get the window saying “Device is unsecured” 
![IMG_4510](https://github.com/roothide/Bootstrap/assets/130188733/41e1132b-2d9e-4baf-ad5a-8a3fb0fa1bd8)



https://apps.apple.com/kw/app/gulf-bank-mobile-banking/id1577206679

^ this is the link to my banking application

**Comment by dleovl** [comment]
> Hello, i have recently encountered my banking app that detect my JB, iphone 14 pro max ios 16.6.1, i have been using the app without no bypass tweaks and it was fine for almost 2 weeks until yesterday it detected as My device is unsecured Bc of jailbreak. I followed the uninstallation method from A to Z and yet i still get the window saying “Device is unsecured” ![IMG_4510](https://private-user-images.githubusercontent.com/130188733/299631976-41e1132b-2d9e-4baf-ad5a-8a3fb0fa1bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDg0NzksIm5iZiI6MTcwNzEwODE3OSwicGF0aCI6Ii8xMzAxODg3MzMvMjk5NjMxOTc2LTQxZTExMzJiLTJkOWUtNGJhZi1hZDVhLThhM2ZiMGZhMWJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNDQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWU5ZDllYjcyYmViN2QyZWM4YzMxYzYyNzdmZDkyOTdhNDFiZmIyYjhmMTkyYmJkNGIwZTJlZTg5NjQ3ZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9cCNx9LIBRYIOZLpbgFIpBWKd4fF4muxYpm7T11u0k)
> 
> https://apps.apple.com/kw/app/gulf-bank-mobile-banking/id1577206679
> 
> ^ this is the link to my banking application

Sorry for getting back so late. varClean ismn uninstall guide is optional, have you done that?

**Comment by SATIS8CHIMPALEE** [comment]
![IMG_6278](https://github.com/roothide/Bootstrap/assets/47916218/2549dd2d-f984-479e-ad6c-46a35198e979)


TrueMoney Wallet App update to version 5.52.0 for jailbreak detection on bootstrap 

previously version 5.51.0 works fine after downgrade by appstore++

PS. No Filza installed 

https://apps.apple.com/th/app/truemoney/id663885752?l=th

**Comment by m1337v** [comment]
For me Gulfbank works without problems (as far as you can go without being a customer)

Can confirm Truemoney doesn't work without tweaks enabled for it (no Filza, Crane etc. installed and var completely cleaned)

**Comment by SATIS8CHIMPALEE** [comment]
> For me Gulfbank works without problems (as far as you can go without being a customer)
> 
> Can confirm Truemoney doesn't work without tweaks enabled for it (no Filza, Crane etc. installed and var completely cleaned)


After doing varClean I was able to access the app. But only after opening Sileo. It can be detected Even though I didn't install any tweaks.


![IMG_9666](https://github.com/roothide/Bootstrap/assets/47916218/5cbdb58a-dbf8-4aa5-97b8-825e15e80ba4)
![IMG_9667](https://github.com/roothide/Bootstrap/assets/47916218/fcd754d9-41b1-4b56-a38b-4e32b5b28d32)
![IMG_9668](https://github.com/roothide/Bootstrap/assets/47916218/1c820138-7fad-4c5b-923b-b3d4e815be51)
![IMG_9669](https://github.com/roothide/Bootstrap/assets/47916218/c36372ff-bdab-4472-bbac-72d1e45c297c)

**Comment by dleovl** [comment]
You may be able to use a Shortcut to open the app if you have openssh installed.

ssh 127.0.0.1 and rm /var/mobile/Library/SplashBoard/Snapshots/org.coolstar.SileoStore
Open App appname
you will probably need to add a wait inside, though not sure which one.
then use the shortcut on your home screen. clicking notifications will not use the shortcut, so it will have detection.

**Comment by MysticallyQ8** [comment]
yes i have to almost everything that i found in reddit and github yet no solution for it> > Hello, i have recently encountered my banking app that detect my JB, iphone 14 pro max ios 16.6.1, i have been using the app without no bypass tweaks and it was fine for almost 2 weeks until yesterday it detected as My device is unsecured Bc of jailbreak. I followed the uninstallation method from A to Z and yet i still get the window saying “Device is unsecured” ![IMG_4510](https://private-user-images.githubusercontent.com/130188733/299631976-41e1132b-2d9e-4baf-ad5a-8a3fb0fa1bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDg0NzksIm5iZiI6MTcwNzEwODE3OSwicGF0aCI6Ii8xMzAxODg3MzMvMjk5NjMxOTc2LTQxZTExMzJiLTJkOWUtNGJhZi1hZDVhLThhM2ZiMGZhMWJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwNDQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWU5ZDllYjcyYmViN2QyZWM4YzMxYzYyNzdmZDkyOTdhNDFiZmIyYjhmMTkyYmJkNGIwZTJlZTg5NjQ3ZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9cCNx9LIBRYIOZLpbgFIpBWKd4fF4muxYpm7T11u0k)
> 
> > 
> 
> > https://apps.apple.com/kw/app/gulf-bank-mobile-banking/id1577206679
> 
> > 
> 
> > ^ this is the link to my banking application
> 
> 
> 
> Sorry for getting back so late. varClean in uninstall guide is optional, have you done that?

**Comment by jrew20** [comment]
I manage to fixed jailbreak detection, I'm using Gcash app from philippines and the app detected jailbroken even I did not enable from bootstrap.

I fixed it by deleting jb shortcuts in filza from private/var/ folder

you will find shortcuts with white icon
to know that is from jb try to check details the "i" from right then you will see fight "var/jb" I deleted those shortcuts and restart the app and jailbreak detection gone.

**Comment by T5ive** [comment]
> > For me Gulfbank works without problems (as far as you can go without being a customer)
> > Can confirm Truemoney doesn't work without tweaks enabled for it (no Filza, Crane etc. installed and var completely cleaned)
> 
> After doing varClean I was able to access the app. But only after opening Sileo. It can be detected Even though I didn't install any tweaks.
> 
> ![IMG_9666](https://private-user-images.githubusercontent.com/47916218/302487697-5cbdb58a-dbf8-4aa5-97b8-825e15e80ba4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzkwNjQsIm5iZiI6MTcwODg3ODc2NCwicGF0aCI6Ii80NzkxNjIxOC8zMDI0ODc2OTctNWNiZGI1OGEtZGJmOC00YWE1LTk3YjgtODI1ZTE1ZTgwYmE0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxNjMyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWRlZGU1ZjlkMGZhOWJlYTcwMTBiYTNkZjE1MTI4ZDJkZjA3YzAwNzY0YmQ1ZGI5OWE0NmY4NTI1MzFiMTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wpRN6VhrCXLyF_YvhwuFEkQRThOjCcQbz9UdTal_qwE) ![IMG_9667](https://private-user-images.githubusercontent.com/47916218/302487717-fcd754d9-41b1-4b56-a38b-4e32b5b28d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzkwNjQsIm5iZiI6MTcwODg3ODc2NCwicGF0aCI6Ii80NzkxNjIxOC8zMDI0ODc3MTctZmNkNzU0ZDktNDFiMS00YjU2LWEzOGItNGUzMmI1YjI4ZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE2MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZDJmZThhZDI2ZWZiNmYzN2NkZWQxOGYwOThiNTg1NzkxZjljMmI5ZjhjZTAwNWFkMjJmYmFlZjM1OGJiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxoR6JlM-6o-56OByV8gyWtCax5YQRpvyyMd1u3VEv8) ![IMG_9668](https://private-user-images.githubusercontent.com/47916218/302487738-1c820138-7fad-4c5b-923b-b3d4e815be51.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzkwNjQsIm5iZiI6MTcwODg3ODc2NCwicGF0aCI6Ii80NzkxNjIxOC8zMDI0ODc3MzgtMWM4MjAxMzgtN2ZhZC00YzViLTkyM2ItYjNkNGU4MTViZTUxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxNjMyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTk5NzRhMTJhNjkzYWMzZGViYjAxZmZhYTk0OWJhMGExMTc4ZjUxNmZiZTBkOTY0ZDk5Y2I5NzU4Mjc5MDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QXEWMFqbSJAM5-HbPBsIuFMPJhoQ-93Dro9jlAZneuE) ![IMG_9669](https://private-user-images.githubusercontent.com/47916218/302487742-c36372ff-bdab-4472-bbac-72d1e45c297c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzkwNjQsIm5iZiI6MTcwODg3ODc2NCwicGF0aCI6Ii80NzkxNjIxOC8zMDI0ODc3NDItYzM2MzcyZmYtYmRhYi00NDcyLWJiYWMtNzJkMWU0NWMyOTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE2MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTAwYWFhYjYwOWNlOTcwYTAyOTdmMjJjMzAyMTUzMmFhMjlhY2Y3NGMwZjc4MzAyNWFiZmMxMzE5NjRlODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQvBzi2978hWmAwVXxVkMa6g1wewEXQnN74FtKV-SjE)

After doing varClean I still can't access the app
Do you have any tips for fixing it?

**Comment by skell79** [comment]
> will
I tried like 5 times to run "Var Clean" but it just froze up each time.I deleted Filza but I see the files in there.. and I do have Appsmanager and AppStorePlusPlus installed to TrollStore.. could those 2 apps be causing this?

**Comment by dleovl** [comment]
This issue has gone off track, at most list apps and solutions if possible. If you need help for a specific application, please do so in the roothide Discord server (linked on the repositories `README.md`.

**Comment by Double077** [comment]
Picky app : "NAFATH" detects roothide 
![Screenshot 2024-04-18 213816](https://github.com/roothide/Bootstrap/assets/108241747/9ced5e28-7565-406d-94b1-92f9429de0df)

https://apps.apple.com/sa/app/%D9%86%D9%81%D8%A7%D8%B0-nafath/id1598909871

**Comment by roothider** [comment]
> Picky app : "NAFATH" detects roothide Crashes Immediately after opening ![Screenshot 2024-04-18 213816](https://private-user-images.githubusercontent.com/108241747/323721396-9ced5e28-7565-406d-94b1-92f9429de0df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Njg3MjUsIm5iZiI6MTcxMzQ2ODQyNSwicGF0aCI6Ii8xMDgyNDE3NDcvMzIzNzIxMzk2LTljZWQ1ZTI4LTc1NjUtNDA2ZC05NGIxLTkyZjk0MjlkZTBkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxOTI3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQ3MmQyZjNhYTljY2YwMzhlNjE3MzFiMDM5Mjg5OWY2MWUxNjg3ZmQwYTAwNjkzNDYwNGRhNmY2NmU0YmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6lFCadFVNW_UA9b7apdT8CgWbT8lRMyxyh-sy1KNAts)
> 
> https://apps.apple.com/sa/app/%D9%86%D9%81%D8%A7%D8%B0-nafath/id1598909871

roothide Dopamine or roothide Bootstrap?

**Comment by Double077** [comment]
Dopamine

**Comment by roothider** [comment]
> Dopamine

known issue, try this version:
https://filetransfer.io/data-package/MbuoIoLB#link

**Comment by Double077** [comment]
Nice works like a charm thank you

**Comment by honestyan** [comment]
# App Force Closes Due to RootHide Detection

**Issue:**
The app still detects roothide detection and force closes immediately upon launch. This behavior occurs even when no URL scheme-based apps are installed on the device.

**Request:**
I do not want to use `varClean` to address this issue because it may remove my tweak configurations (correct me if I'm wrong). Is there an alternative solution to bypass the roothide detection without compromising my existing tweaks?

**Device Information:**
- App: [Wondr by BNI](https://apps.apple.com/us/app/wondr-by-bni/id6499518320)
- Device: iPhone 13 Mini 16.6.1

**Expected Behavior:**
The app should not force close due to root detection when there are no URL scheme-based apps installed. A solution that doesn't involve removing important tweaks is needed.

**Steps to Reproduce:**
1. Install the app from the [App Store](https://apps.apple.com/us/app/wondr-by-bni/id6499518320).
2. Attempt to launch the app on a device.
3. Observe that the app force closes due to roothide detection.

**Additional Information:**
Any additional debugging or suggestions for bypassing this detection would be appreciated.

CC: @roothider @imnltsa @jrew20

**Comment by honestyan** [comment]
> just delete everythi



> > **Request:** I do not want to use `varClean` to address this issue because it may remove my tweak configurations (correct me if I'm wrong). Is there an alternative solution to bypass the roothide detection without compromising my existing tweaks?
> 
> A lot of the files are detectable. Instead of wiping everything, just delete everything that isn't related to preferences (usually named after the tweak itself and ending in `.plist`).

I just want to make sure, is the tweak's/app's plist related and would it be affected by this? I want to avoid deleting anything essential.

**Comment by honestyan** [comment]
> Try removing all files and directories **BUT** the following and see if it fixes your issue:
> 
> * `/var/mobile/.TrollApps/`
> * `/var/mobile/.serotonin_hidetext`
> * `/var/mobile/Serotonin.jp2`
> * `/var/mobile/Documents/.DynamicCowBackups/`
> * Everything in `/var/mobile/Library/Preferences/` (these are tweak preferences)
> 
> Directories in `Saved Application State` (or `Snapshots`, I really don't know anymore) will be created when applications are reopened (ex. Filza, Sileo). Please ensure these apps are closed and the directories removed before testing. If a file/directory being created when an application is opened causes your application to detect a jailbreak, look into [this 'workaround'](https://github.com/roothide/Bootstrap/issues/48#issuecomment-1929011358).
> 
> @honestyan

Thanks, I followed your instructions, and it worked! There’s no jailbreak detection anymore. What should I do next? I mean to prevent it was happened again.

**Comment by honestyan** [comment]
> > What should I do next? I mean to prevent it was happened again.
> 
> Just keep an eye out on when it's triggered again and do process of elimination when finding out which file/directory is specifically triggering the detection, and either remove it again or use the shortcut method I linked above to automate it.

Just to make sure—by deleting everything except the files and directories you mentioned, there won’t be any negative impact on my apps or jailbreak functionality, right? Let me know if there's anything else I should be cautious about. Anyway, I I will try the shortcut tips tho.

**Comment by honestyan** [comment]
> > Just to make sure—by deleting everything except the files and directories you mentioned, there won’t be any negative impact on my apps or jailbreak functionality, right?
> 
> Majority of it was stuff iOS creates on its own. It's safe to delete.

Can you send me a a docs which OpenSSH tweak? I been try any tweaks on redd*t but I cant find which one the truly one.

**Comment by honestyan** [comment]
> > Can you send me a a docs which OpenSSH tweak? I been try any tweaks on redd*t but I cant find which one the truly one.
> 
> OpenSSH is provided by the Procursus repository and is available in the Procursus(roothide) repository. You can then SSH into `127.0.0.1` and `rm` (or `rm -rf`) the file/directory triggering detection.

gotcha. I owe you one.

**Comment by honestyan** [comment]
> > Can you send me a a docs which OpenSSH tweak? I been try any tweaks on redd*t but I cant find which one the truly one.
> 
> OpenSSH is provided by the Procursus repository and is available in the Procursus(roothide) repository. You can then SSH into `127.0.0.1` and `rm` (or `rm -rf`) the file/directory triggering detection.

![image](https://github.com/user-attachments/assets/a4f5976e-0b39-438b-96c6-fd97772ee0eb) am I did any failure? cause the data not deleted after I ran my shortcuts

**Comment by honestyan** [comment]
> > > > Can you send me a a docs which OpenSSH tweak? I been try any tweaks on redd*t but I cant find which one the truly one.
> > > 
> > > OpenSSH is provided by the Procursus repository and is available in the Procursus(roothide) repository. You can then SSH into `127.0.0.1` and `rm` (or `rm -rf`) the file/directory triggering detection.
> > 
> > ![image](https://github.com/user-attachments/assets/a4f5976e-0b39-438b-96c6-fd97772ee0eb) am I did any failure? cause the data not deleted after I ran my shortcuts
> 
> I would not delete the folders as a whole (probably broke something, not sure) but delete the specific files/directories that trigger detection (ex. a Filza directory inside the `Snapshots` directory). The purpose of this is to remove the offending file/directory then the application is immediately launched after removal using the "Open App" block, causing the application to open flawlessly.

It doesn't delete my folder. am I did something wrong?

**Comment by roothider** [comment]
all packages from procursus use jbroot as the default filesystem root on roothide, ref to: https://github.com/roothide/Developer/blob/main/vroot.md
