### ISSUE TITLE
Can edit system file and keychain-2.db?

### ISSUE THREAD

**Issue by dinhthiet2702** [RootHide/Bootstrap#56]
Hello. Can you answer it for me? 
- How to edit system plist file
- Delete and edit table in /var/KeyChains/keychain-2.db
Thanks you!!

**Comment by dleovl** [comment]
Only way to figure it out is to try it yourself. Please be wary that editing your system files could cause irreparable damage to your device and only you should take responsibility for your mistake. Closing, not Bootstrap related. Use Filza.
