### ISSUE TITLE
Make package failing

### ISSUE THREAD

**Issue by danielyc** [roothide/Bootstrap#79]
When i try to make Bootstrap following the provided instructions. The building process fails with the following error

`> Making all for xcodeproj Bootstrap…
bash: -project: command not found
make[2]: *** [internal-xcodeproj-compile] Error 1
make[1]: *** [internal-xcodeproj-all_] Error 2
make: *** [Bootstrap.all.xcodeproj.variables] Error 2`

**Comment by dleovl** [comment]
https://github.com/dleovl/RootHideBootstrapUnofficialFAQ/blob/main/README.md#how-do-i-build-the-roothide-bootstrap-no-pcmac-required
