### ISSUE TITLE
DLEasy incompatibility

### ISSUE THREAD

**Issue by Migaas001** [roothide/Bootstrap#80]
Hi, I was trying to install DLEasy on bootstrap iOS 17 but I have the next issue, if you may help 

Thanks 
![IMG_7576](https://github.com/roothide/Bootstrap/assets/135570897/5466ea76-8adc-46c0-8ac6-8212ec531b4e)

**Comment by roothide** [comment]
It may be because the tweak is not adapted for ios16+ A12+ devices, you need to contact the developer for updates.

**Comment by dleovl** [comment]
DLEasy will need to be updated for RootHide

**Comment by roothide** [comment]
> DLEasy will need to be updated for RootHide

it works well on roothide dopamine ios15, so it may need to be updated for ios16 arm64e devices

**Comment by dleovl** [comment]
Closing, as this issue is outside the scope of this repository. DLEasy will need to be updated to work on the roothide Bootstrap. Please contact the developer.
