### ISSUE TITLE
RootHide Manager doesn't wanna open

### ISSUE THREAD

**Issue by Tuchan** [roothide/Bootstrap#85]
iOS: 16.1, iPhone 13

<img src="https://github.com/roothide/Bootstrap/assets/43300571/9c76be74-687d-4979-9649-75b0deecd965" width="300"/> <img src="https://github.com/roothide/Bootstrap/assets/43300571/0b99726e-3571-46cc-a0e3-1850e937f33e" width="300"/>

https://github.com/roothide/Bootstrap/assets/43300571/b465b493-72b6-40a1-b030-c2dc2b9cab99

**Comment by roothide** [comment]
1: Check the detailed installation log in sileo
2: zip /var/mobile/Library/Logs/CrashReporter and upload here (via filza trollstore version)

**Comment by Tuchan** [comment]
<img src="https://github.com/roothide/Bootstrap/assets/43300571/93e78917-defb-4ffc-b1ac-a5a72bb6d339" width="300"/>
<img src="https://github.com/roothide/Bootstrap/assets/43300571/db50f8e7-7350-4055-af74-d622c76dfd2e" width="300"/>
<img src="https://github.com/roothide/Bootstrap/assets/43300571/c419ddc5-5b39-4b4d-ab63-9964e1b1c3db" width="300"/>

https://cdn.discordapp.com/attachments/1181376313966215178/1194020461491802132/roothide_zips.zip?ex=65aed535&is=659c6035&hm=8b48e4f5c8e030918933fb284a3ae6ea040dd1b5fded192cc871301322cc82ef&

**Comment by Tuchan** [comment]
https://tuchan.fun/roothide_zips.zip

when you download, please react with anything under this message so that I can delete it

**Comment by uphantom89** [comment]
I got the same issue when installed roothide manager while using bootstrap beta 2 version. However, the issue gone, I can install Roothide without error when using bootstrap beta 4.2. 
Roothide can open, and "clean file" function work, but all the apps toggle button can not be toggled, same issue happen for "Whitelist" toggle button.

**Comment by dleovl** [comment]
> I got the same issue when installed roothide manager while using bootstrap beta 2 version. However, the issue gone, I can install Roothide without error when using bootstrap beta 4.2. Roothide can open, and "clean file" function work, but all the apps toggle button can not be toggled, same issue happen for "Whitelist" toggle button.

The manager applications toggles are only used for roothide Dopamine.

**Comment by dleovl** [comment]
Closing. If this issue persists with the latest Bootstrap (following a proper uninstallation), make a new issue.
