### ISSUE TITLE
“Developer Mode not enabled” when it is

### ISSUE THREAD

**Issue by neon443** [roothide/Bootstrap#94]
![0EBE39EE-3F22-417A-B772-925E077A395B](https://github.com/roothide/Bootstrap/assets/69979447/b778ae0a-d6d5-4bd2-bc0d-44e87f020e77)

**Comment by roothide** [comment]
whats your device and ios version?

try disable developer mode, reboot, enable developer mode, reboot again.

**Comment by neon443** [comment]
iPad 8th gen 16.1.1 and I've tried that

**Comment by roothide** [comment]
try to use ts2.0.9 to enable developer mode

**Comment by roothide** [comment]
1: use filza to run /var/containers/Bundle/Application/.jbroot-xxxxxxx/basebin/devtest and take a screenshot

2: zip /var/mobile/Library/Logs/CrashReporter and upload to here

**Comment by neon443** [comment]
[_com.apple.Pasteboard.vR0rBx.zip](https://github.com/roothide/Bootstrap/files/13916561/_com.apple.Pasteboard.vR0rBx.zip)
![3CD74E68-932F-42B3-AE28-F44B7F8E61AC](https://github.com/roothide/Bootstrap/assets/69979447/c4ee11e2-7acd-481f-b7b0-8dd404c16bab)

**Comment by roothide** [comment]
you may try uninstalling the bootstrap app and then reinstalling it, some users with the same issue fixed it this way.
