### ISSUE TITLE
code(255) stderr: when enabling applications in AppEnabler

### ISSUE THREAD

**Issue by xingxichen** [roothide/Bootstrap#95]
code255
其他app都正常
![IMG_4532](https://github.com/roothide/Bootstrap/assets/50514349/01fcaab3-a9f3-44aa-84af-b61c679562a3)

**Comment by xingxichen** [comment]
现在是beta4.2,但是之前的版本也有这个问题。这是链接，但是我重新安装又好了。🥵
https://apps.apple.com/cn/app/%E5%BE%AE%E4%BF%A1/id414478124

**Comment by punz1738** [comment]
Having same issue with Serotonin

**Comment by dleovl** [comment]
> Having same issue with Serotonin

Serotonin does not need to be enabled.

**Comment by punz1738** [comment]
> > Having same issue with Serotonin
> 
> Serotonin does not need to be enabled.

Ah okay makes sense thank you so much

**Comment by deep0d0** [comment]
Also getting this error when enabling YouTube app

**Comment by dleovl** [comment]
Closing. If your issue persists on the latest version, please create a new issue.
